name: SLIDES
on:
  # push on master branch: build slides (pandoc)
  push:
    branches: [master]
  # manually triggered: build slides (pandoc)
  workflow_dispatch:


jobs:
  # build slides (pandoc): "make slides"
  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cagix/pandoc-lecture@master
        with:
          make-target: 'make slides'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: _slides
          publish_dir: pdf/
          force_orphan: true
